### PR TITLE
Ensure support for Python 3.11/3.12

### PR DESCRIPTION
**Pull request by Jamim**
Hello @sonic182,

I believe it's a great time to declare support for modern Python versions.
So I'd like to propose changes that:
  * enable testing for Python `3.10`-`3.12` and PyPy `3.7`-`3.10`
  * update `classifiers` at `setup.py`
  * fix incompatible test requirements
  * bump [Node.js](https://nodejs.org/en/about/previous-releases) to `20`
  * fix testing with `tox` for Python `3.12`
  * reveal [a PyPy compatibility issue](https://github.com/Jamim/aiosonic/blob/feature/python-support/tests/test_aiosonic.py#L493-L497)

A corresponding test run might be reviewed here:
https://github.com/Jamim/aiosonic/actions/runs/6837246535

Best regards!

### CODE REVIEW

**Comment by sonic182** [comment]
Seems very nice!!

The only thing is that the CI did not run, I think it is by the rules in the ci.yml

**Review by sonic182 — CHANGES_REQUESTED** [review]
Can you add the rule to run the CI on pull requests please?

**Comment by Jamim** [comment]
Sure! I've added the requested rule.

**Comment by sonic182** [comment]
Very Thanks! :+1:

**Pull request merged**
